[project]
requires-python = ">= 3.11"

[tool.black]
line-length = 100

[tool.coverage.run]
omit = [
    # omit this single file
    "praktikum.py",
    "praktikum/ingredient_types.py"
]

[tool.pytest.ini_options]
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true

